spec/index.adoc

Fix a minor typo

---

spec/index.adoc

This fixes Issue #41 following the suggestions by @nomeata

Properly initialize the `cycles_refunded` field of `Params`

---

README.md
spec/changelog.adoc
spec/http-gateway.did
spec/ic.did
spec/index.adoc

Release containing:
- HTTP gateway protocol
- Fixes to cycles security
- Canister cycles use

Issue release 0.18.5

---

README.md
spec/index.adoc
thys/IC.thy
thys/ROOT

This PR contains a translation and adjustments of Helge's Coq model for a subset of state transitions, proofs of cycle monotonicity for these transitions, and updates to the textual specs based on the formal model.

Upload Isabelle/HOL model and update textual specs

---

spec/index.adoc

Currently this NOTE is not encapsulated by a nice box like the rest of the notes.

Fix the formatting of a NOTE in the doc

---

spec/index.adoc
theories/IC.thy

thanks to @jwiegley for pointing it out

Editorial edit: Pass `Env` to `inspect_message`

---

spec/index.adoc
theories/IC.thy

Update effective canister ID specification.

update spec of ECID

---

spec/index.adoc

Signed-off-by: Dominic Woerner <dominic.woerner@dfinity.org>

wrong flag name for upgrading http requests to update calls

---

spec/changelog.adoc

Update the changelog to reflect the changes from release 0.18.6.

Update master changelog

---

spec/changelog.adoc
spec/ic.did
spec/index.adoc

Release 0.18.7 of the interface specification
* HTTP request API
* Reserved principals

Cut release 0.18.7

---

spec/changelog.adoc

Merge 0.18.8 back to master

---

spec/index.adoc

fixes this [issue](https://github.com/dfinity/interface-spec/issues/121)

specify reject behaviour for stopping, stopped, and empty canisters

---

spec/changelog.adoc

changelog update

---

spec/index.adoc

Updates conditions on WASM module validation in line with the replica implementation.

update conditions on WASM module validation

---

spec/_attachments/interface-spec-changelog.md
spec/index.md

Replica code MRs: https://gitlab.com/dfinity-lab/public/ic/-/merge_requests/12761 and https://gitlab.com/dfinity-lab/public/ic/-/merge_requests/13289

add conditions on read_state paths

---

spec/_attachments/interface-spec-changelog.md

Release v0.20.0 of Interface Specification.

release v0.20.0

---

README.md

This PR adds the link to a preview of the master branch into README.md.

add link to preview canister into README.md

---

spec/_attachments/ic.did

i formatted the document for a consistent style and added the missing convenience types to 
close #269

add convenience types for canister management methods

---

spec/_attachments/interface-spec-changelog.md

chore: release 0.23.0

---

spec/_attachments/interface-spec-changelog.md
spec/index.md

This PR updates the subnet read state conditions to match the replica implementation.

fix: update subnet read state conditions to match the implementation

---

spec/index.md

Closes https://github.com/dfinity/interface-spec/issues/289

fix: memory allocation description

---

spec/_attachments/interface-spec-changelog.md

This PR merges the changelog of release v.0.24.0 into the master branch.

feat: release 0.24

---

.github/workflows/preview-deployment.yml
README.md
docusaurus/package-lock.json
docusaurus/package.json
spec/index.md

this is a continuation of https://github.com/dfinity/interface-spec/pull/291 that uses hidden heading tags to preserve custom heading IDs

chore: use hidden heading tags

---

spec/index.md

This PR fixes the rendering of system imports by wrapping their overview into a code environment.

fix: code environment for system imports

---

spec/index.md

This PR fixes the canister memory usage by modelling chunk store memory usage and simplifying notation.

fix: canister memory usage - simplify and model chunk store

---

spec/_attachments/interface-spec-changelog.md

This PR releases Interface Specification v0.28.0.

feat: release v0.28.0
