spec/index.adoc
We no longer enforce a limit on the amount of cycles a canister can
hold, so this limit should be removed from the spec.
=> EXC-783: Remove limit on Cycles in a canister

spec/ic.did, spec/index.adoc
This PR provides the specifications for the feature IC-530: Canister HTTP requests.
The spec explains what are the constraints without explaining intricacies related to the underlying protocol. 
For this first iteration:
* the maximal size of the response is defined to `2MiB` (maximal size of a message in the consensus queue). 
* no mentions of cycles-related charges; Specifying additional cost that this call will incur should be added in the developers' guide, [Computation costs](https://smartcontracts.org/docs/developers-guide/computation-and-storage-costs.html ), once the cost is established.
=> IC-530:Canister HTTP requests

spec/index.adoc
The system now supports multiple encodings of the `wasm_module` field: raw Wasm and gzip-compressed Wasm.
We pick the appropriate decoding based on the magic number of the binary.
=> feat: specify how to install GZIP-compressed modules

spec/index.adoc
Follow up of Canister HTTP requests: https://github.com/dfinity/interface-spec/pull/7. 
Motivation: The implementation introduces an "internal query" that does not provide a caller id because the transformation function of the HTTP response is triggered by an internal component from the networking layer.
Given that the transform function is exported as `canister_query`, for consistency, we will return the canister management id if `msg_caller_copy` is called inside the transformation function.
=> Canister http request - Add a note about the expected caller id

spec/index.adoc
The section on `Certificate`s currently refers to an algorithm named `check_delegation` in the `Delegation` section, but this algorithm is named `check_delegations` (note the additional "s"). This change fixes this inconsistency by renaming the algorithm to `check_delegation`.
On naming: Although the algorithm in fact verifies a *chain* of delegation*s* (i.e., potentially multiple), the provided parameter is just a single delegation, so I opted to use the singular. We could also consider directly naming this, e.g., `check_delegation_chain`.
=> Fix inconsistency in naming algorithm to verify a delegation

spec/ic.did, spec/index.adoc
This MR enhanced the status of the canister with the freezing threshold in cycles. 
This data will be used by the developers and can be used to check when the canister is approaching the freeze threshold in cycles which would mean that the canister may start behaving like a frozen one. In this case, certain operations may fail because there is not enough balance to perform the operation and still have the leftover cycles above the threshold.
=> Canister status - Add Freezing threshold in cycles

spec/ic.did
This MR updates the candid return type for the `http_request` management method. A `Reply` will contain the `http_response`, while any error encountered in IC will be reflected via the `Reject` (reject_code, reject_message).
=> IC00 HTTP request - Return error via Reject

spec/ic.did, spec/index.adoc
We propose two new system APIs for the upcoming threshold ECDSA feature in the management canister.
=> System API for threshold ECDSA

spec/ic.did
Due to a merge mistake in #6, a previously removed type re-appeared. So this PR fixes the problem.
=> Fix previous merge mistake

spec/index.adoc
previously, the type in the `CanisterModule` was bogus (it was not
passing the `WasmState` around). Thanks to @jwiegley for spotting.
=> Editorial: Fix use of heartbeat in Message Execution rule

spec/index.adoc
=> Editorial: Fix reference to method name in Message Execution rule

spec/index.adoc
probably a fallout from the cherry-pick in
d442081f8c060017708f583c85d327f39e3404de.
=> Editorial: M.receiver, not C.callee

spec/changelog.adoc
now that this repo no longer contains what is in
https://github.com/dfinity/ic-hs it seems prudent to remove the non-spec
entries from the changelog. Will also make more sense on
https://smartcontracts.org/docs/interface-spec/index.html#changelog
=> Clean up changelog (Editorial)

spec/ic.did, spec/index.adoc
This PR as discussed in a previous [PR](https://github.com/dfinity/interface-spec/pull/18#issuecomment-1090303378), adds the idle consumption rate of the resources of a canister. This can be used to compute the freezing threshold in cycles.
=> Canister status - Add idle consumption rate 

default.nix, spec/changelog.adoc, spec/http-gateway.did, spec/index.adoc
We have had the HTTP gateway for a while now, but 
* we didn’t have a public record of the expected Canister interface, with the authorative Candid fragment
* we already have multiple implementations (`icx-proxy` and the service worker), and people we looking at the implementations to understand how thing work.
* we see new features being implemented in one, but not the other implementation, and they start to diverge
* some features are only implementation-defined (e.g. the certification fallback to `index.html`)
* the interaction of new features (e.g. certificate, upgrade to update and streaming) is ill or at least vaguely defined.
So I think we urgently need a proper specification for the HTTP Gateway protocol, and a place to host this. The IC Interface Spec is a natural place, so here …
=> Specify the HTTP Gateway protocol

.netlify.sh, netlify.toml
It is really very useful use to have rendered previews of PRs easily available online, and also of the `master` branch, and Netlify is the easiest way to to achieve that.
This PR, which fixes #9, provides a simple netlify configuration using the existing nix builds. No further configuration or infrastructure is needed (e.g. no extra caches or such).
So all we need to get this live is 
* merge this PR
* someone with sufficient permissions creates a new site at netlify (I suggest `ic-interface-spec.netlify.app` to begin with) and adds this repo
I think the default configuration works just fine, and will create preview deployes for PRs. 
They will look like this: https://ic-spec-pr-preview.netlify.app/
=> CI: Add a netlify configuration

spec/index.adoc
which is used in the “state after” section
=> Editorial: Correctly introduce the variable A

spec/index.adoc, spec/requests.cddl
This change adds a new field to reject responses:
implementation-specific textual error code.  Tools such as DFX could use
these codes to provide better diagnostic to users and propose recovery
paths.
The spec reserves error codes starting with "IC" for the DFINITY
implementation.
In future, we might fix semantics of specific error codes in the spec.
=> feat: implementation-specific error codes

spec/ic.did, spec/index.adoc
We would like to add a new parameter for the HTTP request feature to specify the maximal size of the response.
This will be used for charging the requests and for limiting the bandwidth used by the feature.
=> Add a maximal response size parameter for the HTTP Request feature

spec/changelog.adoc, spec/ic.did, spec/index.adoc
Based on previous MR  https://github.com/dfinity/interface-spec/pull/31, which introduced `idle_cycles_burned_seconds`, and a few follow-up discussions, there was reached the agreement that we should avoid `float` types in the replica. 
This MR:
* change `idle_cycles_burned_seconds` the type from float to nat.
* due to the previous change,  we lose some precision. Therefore, to increase the precision we will provide `idle_cycles_burned_hour`.
* fix: remove `freezing_threshold: nat;` from the canister status. It is already specified in the `definite_canister_settings `.
=> EXC-1122: Update idle_cycles_burned

spec/ic.did, spec/index.adoc
The network parameter is necessary in that endpoint for us to distinguish whether the user
wants the fee percentiles of mainnet or testnet.
Note that this change is not backward-compatible, but the API was never made public so
this change is acceptable.
=> Add network parameter to bitcoin_get_current_fee_percentiles

spec/index.adoc
Because `freeze_threshold` can be equal to zero, the equation
```
idle_cycles_burned_per_day = freezing_limit * seconds_per_day / freeze_threshold
```
might yield undefined value (if `freeze_threshold = 0`).
Hence, we make  `idle_cycles_burned_per_day` unspecified and derive `freezing_limit` from  `idle_cycles_burned_per_day` and `freeze_threshold`.
=> define freezing_limit in terms of idle_cycles_burned_per_day

spec/changelog.adoc, spec/index.adoc
Canisters are currently allowed to execute query calls even if when they are frozen. This can lead to confusion as canisters with heavy or query-only workload can look as if they're completely fine and can catch canister owners off-guard as their canister can get uninstalled even they are not proactive enough to monitor its cycles balance closely. On top of this, query calls will be charged cycles anyway in the future, so disallowing queries to frozen canisters seems like a reasonable thing to enforce.
=> Update query call prose to cover the case of frozen canisters

spec/index.adoc
Textual identifiers are actually used in the spec, namely in the HTTPS interface referencing the effective canister id. So the note stating that they are purely informational should be removed.
=> Remove note on textual identifiers

spec/index.adoc
The formulation is taken from the linked specification: https://www.w3.org/TR/2003/REC-PNG-20031110/#5CRC-algorithm
=> remark on big-endian encoding of 32-bit CRC

spec/index.adoc, theories/IC.thy
Currently, a canister with open call contexts cannot move to a stopping state even if all its open call contexts are marked as deleted (e.g., after its code was uninstalled). Although it's harmless to have an empty canister with open call contexts that are all marked deleted, if somebody installed a new canister module and later wanted to upgrade it, the open call contexts that are marked deleted could prevent the transition to the stopped state, making the canister dangerous to upgrade.
To resolve the issue described in the previous paragraph, I propose to update the definition of when a canister is ready to be stopped to only consider the existence of open call contexts that are not marked deleted.
The replica MR is linked here: …
=> Deleted call contexts do not prevent canister from reaching Stopped state

.github/workflows/isabelle.yml, .gitignore, README.md, spec/changelog.adoc, spec/index.adoc, spec/requests.cddl, theories/IC.thy, theories/ROOT
Main changes:
* Canister access to performance metrics
* Query calls are rejected when the canister is frozen
* Support for implementation-specific error codes for requests
* Deleted call contexts do not prevent canister from reaching Stopped state
* Update effective canister id checks in certificate delegations
* Formal model in Isabelle
And a few clarifications and corrections.
=> Cut release 0.18.6

spec/index.adoc
In Bitcoin, fees are measured in `sat/vbyte` (as opposed to `sat/byte`). This PR makes it clear that our IC method `bitcoin_get_current_fee_percentiles` is consistent with standard Bitcoin clients and returns fee percentiles in `sat/vbyte` as well.
The concept of virtual bytes (`vbytes`) and weight units is specified [here](https://en.bitcoin.it/wiki/Weight_units).
=> Bitcoin fees are measured in sat/vbyte

spec/index.adoc
This change defines a way for apps to indicate that a blob is _not_ a valid principal.
This feature is particularly useful when an app wants to re-use the textual encoding for principals but does not want to confuse the system with blobs that _accidentally_ look like a valid principal (see https://github.com/dfinity/ICRC-1/pull/55 for an example).
=> feat: a spec for reserved principals

spec/index.adoc
Add a (forgotten) case to the definition of `find_label`:
```
find_label(l, [Leaf _]) = Absent
```
Note that `well_formed(tree)` implies that either
- `tree` is `Leaf v`: then `flatten_forks(tree) = [Leaf v]` and the new case from this PR triggers (before `find_label` would return `Unknown` which is unnecessarily conservative);
- otherwise, `flatten_forks(tree)` cannot contain any tree of the form `Leaf v`; hence we don't need to care about leaves in `find_label` beyond the case `[Leaf v]`.
=> chore: add a case to find_label

spec/index.adoc
As we envision a need to change the type of the transform function soon, we declare the API for http_request experimental for now, and will remove this once we decide on the required changes and make them.
=> Declaring http_request API experimental

spec/index.adoc
Rationale: Timo's vision is that we might have a lot of principal types one day. Would be nice to keep the most significant bit unreserved to simplify variable-length encoding of the tag.
=> fix: use 0x7f for reserved principals

spec/ic.did, spec/index.adoc
It has been decided to add a blob that represents any necessary context for the transform function, as an argument for the http_request method, and for the transform function.
=> http_request: Add transform context

spec/index.adoc, theories/IC.thy
Currently only controllers can request `canister_status` from the management canister. This PR changes the interface spec to make this query also available to the canister itself.
=> allow a canister to query its own status

spec/index.adoc
For canisters with gzipped wasm module, the module hash is computed on the compressed module. To be consistent with the spec, this means we have to consider the compressed module as _the module_. The previous version of the spec was a bit ambiguous, so this PR attempts to clarify this.
=> Clarify that canister modules can be compressed

spec/index.adoc
The corresponding [change](https://github.com/dfinity/agent-rs/pull/389) of the Rust change is already merged in and passes all pre-master and hourly tests on the IC repo.
=> avoid ever bypassing subnet delegation check

spec/index.adoc
Initially we wanted to restrict the port numbers to prevent access to replica services, but we found a way around this and the restriction is no longer in place. This PR removes the corresponding sentence from the spec.
=> IC-530: Remove port number restrictions

spec/ic0.txt, spec/index.adoc, theories/IC.thy
A *canister state counter* (represented as an unsigned integer) guaranteed to be incremented upon every change of the canister's code and settings is introduced. It is available to the canister via a system API call.
This PR only introduces the concept of a canister state counter. Its application will follow in separate PRs. Here we outline the anticipated applications of the canister state counter:
- used instead of *canister generation counter* proposed [here](https://github.com/dfinity/interface-spec/pull/19) for the sake of safe instantaneous (i.e., without stopping the canister) upgrades that handle all outstanding callbacks properly
- used instead of *canister history index* [here](https://github.com/dfinity/interface-spec/pull/103) to identify the canister's code version that …
=> Introduce a canister state counter

spec/index.adoc
I also removed some old warnings about the `stable64` API which don't apply anymore.
=> Mention maximum stable memory size

spec/index.adoc
This PR cleans up and extends some parts of the Bitcoin integration API:
- The plan is no longer to resubmit transactions periodically. The functionality of the `send_transaction` endpoint is updated accordingly.
- The fee API was underspecified in that it didn't specify what method is used to compute the fee percentiles. The text is updated to make this explicit.
=> Changes to the Bitcoin integration API: Sending transactions and computing fees

spec/index.adoc, theories/IC.thy
The name "canister state counter" could be confusing because the counter is not incremented upon every change of the canister state. Hence, we agreed to rename it to "canister version".
=> rename canister state counter to canister version

spec/index.adoc
A maximal request size should be specified, otherwise the canister gets a 413 error referring to Content-Length even if the canister request and the server response has low Content-Length (e.g., because the request has large headers). It is also not clear how the request size is bound in the implementation so I propose a symmetric upper bound as for responses.
The header name and value length is restricted for implementation reasons.
=> tighten limits of canister http_request

spec/ic0.txt, spec/index.adoc
I found the section regarding encoding of certificates a bit difficult to follow at first, namely because I was not familiar with CDDL. Google searches will return links regarding "Common Development and Distribution License". Of course if you read the whole spec from start to finish then you will eventually find more information regarding CDDL, but I don't believe this is the way that everyone will read the spec. So I propose adding intro sections near the beginning of the document regarding CDDL and CBOR that can be referenced anywhere these technologies are mentioned.
Other smaller changes in this PR:
- replaced links to obsolete CBOR spec with the current spec
- Fixed one instance of "internet computer" -> "Internet Computer"
=> Add CBOR and CDDL intro sections

spec/ic.did, spec/index.adoc
This PR adds an optional `specified_id` argument to `provisional_create_canister_with_cycles` which is going to be used by dfx in order to allow users to install third-party canister dependencies for their canisters locally under the same ids that these canisters have on mainnet.
=> Add optional canister_id argument to provisional_create_canister_with_cycles

spec/ic0.txt, spec/index.adoc
Canister Timers are allowed in post-upgrade and init and it is easy to assume that they are also okay in pre-upgrade.
=> RUN-509: Enable Canister Timers in pre-upgrade

spec/index.adoc, theories/IC.thy
The canister global timer is deactivated upon installing code to a canister and thus the init function of the WASM module sees the global timer equal to zero. This PR fixes that "typo" in the formal part of the specification.
=> fix timer spec in install

spec/index.adoc
If a canister ID C is taken by a canister created with specified_id = Some C, then subsequent canister creation with specified_id = None can fail if the last_generated_canister_id is equal to C which is already taken.
=> canister creation can fail after providing specified_id

spec/index.adoc
Several people have asked about whether send a call request type to a query method changes the canister state. In this PR I try to make it more explicit that the state will not be changed.
=> Make replicated query semantics more explicit

spec/index.adoc
This change extends the specification of representation-independent hashing to handle signed integers.
Motivation: DFINITY's ICRC-1 ledger hashes blocks and transactions using the representation-independent hash from the Interface Spec. The new approve transactions allow negative amounts, so we must extend the spec to be able to hash such transactions.
=> feat: specify representation-independent hash for integers

spec/index.adoc
https://forum.dfinity.org/t/https-api-read-state-status-code-429-can-only-request-up-to-1-paths-for-request-status/19007
=> allow multiple request_status paths for a single request ID in read_state

spec/index.adoc, theories/IC.thy
Currently, certified variables are reset to empty if the canister is uninstalled, but if the canister is reinstalled. This MR makes this behavior consistent.
=> reset certified variables upon canister reinstall

spec/ic0.txt, spec/index.adoc
This PR adds a new system api call to allow a canister to check whether a given principal is one of its own controllers. This is a useful check for canisters and it has come up in various contexts, for example when canisters want to perform some access control on their methods based on whether the caller is a controller.
=> feat: Add a system api call to check whether a given principal is a controller

spec/index.adoc
This PR models access restrictions to System API from the WebAssembly module's `start` function by adding a "start" context `s` to the execution state and enforcing the access restrictions from the `ic0.txt` file in the pseudocode definitions of System API implementation. This PR also rearranges the pseudocode definitions of System API implementation according to the `ic0.txt` file.
=> add start context for ic0 and rearrange ic0 imports according to ic0.txt

spec/index.adoc
In some discussions, people assumed that the `bitcoin_send_transaction` endpoint guarantees delivery to the mempool. This commit adds a clarification that explicitly states that delivery to the mempool is not guaranteed.
=> Clarification to `bitcoin_send_transaction` API

spec/index.adoc
Strengthens the requirements for an HTTP request to be valid if delegations are provided:
1. Delegations must not contain any cycles or be self-signed.
2. The number of `targets` that can be specified in each delegation is limited to 1000.
The length of the delegation chain is at most 20.
=> CRP-1951: forbid cycles and self signed delegations in HTTP requests

spec/ic0.txt, spec/index.adoc
The mainnet's WASM execution engine is going to convert calls to stable memory system API into native memory operations which makes it challenging to prevent calls to stable memory system API in the WASM start function. Since we do not see any important reason to prevent such calls in the WASM start function, we adjust the specification to enable them.
=> enable calling stable memory system API in WASM start function

spec/index.adoc
BIP32 allows a derivation depth of at most 255, and we enforce this limit.
FOLLOW-1013
=> Update the interface spec to describe the limit on threshold ECDSA derivation paths

spec/index.adoc
As we start every message execution with an empty execution state,
the `response_data` added by the `ic0.msg_reply_data_append` system call
and not committed using the `ic0.msg_reply` gets dropped at the end
of the current message execution.
In other words, it's impossible to append the reply data across await points.
=> chore: minor clarification

spec/index.adoc
Corresponding replica code:
```
pub(crate) fn representation_indepent_hash_call_or_query(
request_type: CallOrQuery,
canister_id: Vec<u8>,
method_name: &str,
arg: Vec<u8>,
ingress_expiry: u64,
sender: Vec<u8>,
nonce: Option<&[u8]>,
) -> [u8; 32] {
use RawHttpRequestVal::*;
let mut map = btreemap! {
"request_type".to_string() => match request_type {
CallOrQuery::Call => String("call".to_string()),
CallOrQuery::Query => String("query".to_string()),
},
"canister_id".to_string() => Bytes(canister_id),
"method_name".to_string() => String(method_name.to_string()),
"arg".to_string() => Bytes(arg),
"ingress_expiry".to_string() => U64(ingress_expiry),
"sender".to_string() => Bytes(sender),
};
if let Some(some_nonce) = nonce {
map.insert("nonce".to_string(), Bytes(some_nonce.to_vec()));
} …
```
=> add sender and ingress_expiry to the example request id calculation

spec/index.adoc, theories/IC.thy
This PR reverts #83 and adds an invariant that stopped canisters do not have any call contexts (in particular, stopped canisters do not have any call contexts marked as deleted) with a corresponding extension of the formal model.
=> Deleted call contexts again prevent canister from reaching Stopped state

spec/index.adoc, theories/IC.thy
This MR makes the following adjustments to the "Call context removal" transition and its formal model:
- "the call context has been replied to" is replaced by "the call context does not need to respond" because the former sounds like it refers to outstanding replies to this call context (instead of the reply from this call context to its origin) that are considered in the remaining conditions
- removes the condition
```
S.call_contexts[Ctxt_id].origin = FromSystemTask
∀ FuncMessage M ∈ S.messages. M.call_context ≠ Ctxt_id
```
because it implies that `needs_to_respond` is false (a system task does not await a response and a FuncMessage is never in the message queue when a Call context removal transition can be taken; this is because a FuncMessage is only added by transitions that need to …
=> revise Call context removal transition

spec/index.adoc, theories/IC.thy
This MR makes the following adjustments to the "Call context starvation" transition and its formal model:
- drops the condition `S.call_contexts[Ctxt_id].origin ≠ FromSystemTask` that is implied by `S.call_contexts[Ctxt_id].needs_to_respond = true`
- adds a condition referring to call contexts kept in the Stopping canister status (omitted before)
=> revise Call context starvation transition

spec/ic.did, spec/index.adoc
This PR makes the following adjustments:
- add missing `sender_canister_version` field to `provisional_create_canister_with_cycles` request
- add notes on the order of controllers in management canister call responses and canister history
=> add missing sender_canister_version and note on order of controllers

spec/index.md
This MR fixes links in the main specification text:
- resolve redirects according to w3 validator
- fix typos in link titles and targets
- remove unused anchors
=> fix links according to w3 link validator

spec/index.md
This PR fixes the definition of `lookup_path` and replaces `lookup` by `lookup_path` incl. fixing arguments where appropriate. The issue has been reported by @oggy-dfin .
=> fix definition of lookup

spec/_attachments/interface-spec-changelog.md, spec/index.md
The two features (Bitcoin Integration and HTTP outcalls) have been running in production for several months with enough stability to consider them non-experimental anymore.
=> chore: Remove experimental label for Bitcoin api, ECDSA api and HTTP outcalls

spec/index.md
The replica implementation does not allow the cycle balance to drop below the freezing limit due to transferring cycles in a new call.
=> refine system API conditions on transferred cycles to calls wrt freezing limit

spec/index.md
This PR refines conditions on effective canister ID in the URL of HTTP requests: it specifies that the effective canister ID must be contained the canister ranges of a subnet (before there was only a note about this for the IC mainnet).
=> refine conditions on effective canister ID

spec/index.md
This PR adds a note on `canister_inspect_message` being executed by a single node, the consequences of which I found quite surprising (an update call submitted *after* another update call completes can still fail due to `canister_inspect_message` being invoked on an outdated state of the single node receiving the update call HTTP request).
=> add note on canister_inspect_message being executed by a single node

spec/index.md
Update the specification of `ecdsa_public_key` management canister call based on compliance test findings.
=> update ecdsa_public_key specs

spec/_attachments/interface-spec-changelog.md, spec/index.md
This MR adds a note on confidentiality of values in the certified state tree that can be read via HTTP requests.
=> add note on confidentiality of values in certified state tree

spec/index.md
This PR fixes an oversight when merging composite queries and recent WASM module requirements changes.
=> add canister_composite_query to WASM module requirements section

spec/index.md
This PR turns the explanation of path lookup values into more formal definition of their meaning.
=> refine definition of path lookup values

spec/_attachments/interface-spec-changelog.md, spec/http-gateway-protocol-spec.md
This PR clarifies under which conditions the HTTP Gateway can allow for arbitrary certification version in the canister's response.
=> add note on supported certificate versions in HTTP Gateway

spec/index.md
This PR fixes formatting of the specification of fields in HTTP read_state requests and responses.
=> fix formatting of HTTP read_state request and response definitions

spec/_attachments/interface-spec-changelog.md, spec/index.md
This PR tightens the conditions on requested paths in HTTP read_state requests: it forbids to request paths that cannot be present in the state tree according to its definition.
=> update conditions on requested paths in HTTP read_state requests

spec/index.md
This PR points out explicitly that stable memory is cleared during reinstall. Currently, this is only apparent when reading the formal part of the specification (Abstract transitions).
=> point out that stable memory is cleared during reinstall

spec/index.md
This PR refactors algorithms checking certificate delegations to make them type-correct and thereby also better readable.
=> refactor delegation checking algorithms

.gitignore, netlify.toml
This PR removes the netlify.toml file which is not needed anymore (since we aren't using Netlify anymore) and removes Isabelle/HOL formal model paths from .gitignore (since we aren't developing this model anymore).
=> cleanup netlify.toml and .gitignore

.github/workflows/check-cddl-candid.yml, spec/_attachments/ic.did, spec/index.md
There are a number of applications, particularly frontends, that require some signal as to whether or not some event on the Bitcoin chain has happened. For example, a frontend can allow you to make a Bitcoin transaction, and it wants to auto-refresh and display a signal once the transaction has been mined.
Currently, frontends cannot query the Bitcoin API because it requires cycles. They'd either need to proxy their requests via their own canister, or rely on a block explorer. The former is expensive and slow, while the latter is unideal given that the IC provides its own Bitcoin API.
This commit adds query endpoints to the Bitcoin API. They are query methods enforcing that they can only be called in non-replicated mode. The query endpoints allow frontends to query information about the …
=> feat: add query endpoints to the Bitcoin API

spec/_attachments/interface-spec-changelog.md, spec/index.md
This MR adds a check that a canister receiving an ingress message is Running before the ingress message is marked as `Received`. This is because update calls to Stopping/Stopped canisters are rejected anyway and thus it doesn't make sense to accept such an ingress message.
This MR also cleans up the conditions on ingress messages to provisional API (controller check is dropped for the provisional API).
=> ingress messages to canisters that are not running cannot be received

spec/_attachments/interface-spec-changelog.md, spec/index.md
The current limit is not enough for C++ and Python languages as discussed on the forum: https://forum.dfinity.org/t/wasm-module-defined-globals-which-exceeds-the-maximum-number-allowed-200/
=> Increase max number of WASM globals

spec/index.md
This PR specifies the behavior of `ic0.msg_reply_data_append` and `ic0.call_data_append` in case the accumulated data exceeds the maximum limit imposed by the system.
=> chore: Clarify `*_data_append` behavior

spec/_attachments/interface-spec-changelog.md, spec/index.md
This MR updates the specification of the representation-independent hash computation for the case of maps with nested maps.
=> feat: update representation-independent hash computation

spec/_attachments/interface-spec-changelog.md, spec/_attachments/requests.cddl, spec/index.md
The `senders` field in user delegations is not (going to be) supported in the replica implementation and thus this PR removes this field from the specification.
=> feat: drop senders field from user delegations

spec/http-gateway-protocol-spec.md
Simple typo, later in the specification it is used correctly.
@nathanosdev
=> Fix typo in response verification cert expression header.

spec/index.md
Added the restriction that only controllers can install code uploaded in chunks
=> Only controllers can install chunked code

spec/index.md
This PR reformulates a note on deprecating paths in read state requests for `/api/v2/canister/...` with prefix `/subnet`. They're no longer marked as "will be deprecated", but rather "might be deprecated" and the advise to update is softened.
=> fix: update deprecation note on read state paths

spec/_attachments/interface-spec-changelog.md, spec/index.md
This MR restrict the maximum length of a nonce in a request to 32 since 32 bytes are supposed to provide enough randomness.
=> restrict nonce to be of length at most 32

spec/_attachments/interface-spec-changelog.md, spec/index.md
This MR updates the specification of the `/api/v2/status` endpoint:
- drop `ic_api_version` field that does not reflect the actual specification version implemented by the replica;
- drop `impl_source` field that is not populated by the replica implementation;
- rename `impl_revision` into `impl_version` (dropping the current `impl_version`);
- do not specify `root_key` to be only present in development instances.
The last three changes are catching up with the actual behavior of the IC mainnet.
=> update status endpoint spec

spec/_attachments/interface-spec-changelog.md, spec/index.md
Given that every canister on the IC mainnet is also charged for its message memory usage which is a scarce resource, it is prudent that calls are not long-running. Hence, this PR introduces the possibility to reject `stop_canister` calls at any time.
It also updates the reject code for pending `stop_canister` calls after calling `start_canister` from `CANISTER_REJECT` (4) to `CANISTER_ERROR` (5). This makes sense because `CANISTER_REJECT` (4) is characterized as an "explicit reject by the canister".
=> add new transition rejecting stop_canister calls

spec/_attachments/interface-spec-changelog.md, spec/index.md
This PR merges back the release branch (0.22.0) so the changelog on master is updated accordingly.
=> chore: merge release branch (0.22.0)

spec/index.md
BNs do not serve the field `impl_version` in their response to `/api/v2/status` since subnets might have various `impl_version`s and it's not clear which one should be picked by a BN. So it makes sense to remove this field from the specification.
=> feat: drop impl_version from status endpoint spec

spec/_attachments/interface-spec-changelog.md, spec/index.md
This PR specifies that the IC sends a `user-agent` header with the value `ic/1.0` if the canister does not provide a `user-agent` header in canister HTTPS outcalls.
(This PR also fixes the Markdown syntax of an enumeration in the canister HTTPS outcalls section.)
=> feat: user-agent header in HTTPS outcalls

spec/index.md
This MR replaces concrete reject message text (e.g., "canister not running") in the formal semantics by `<implementation-specific>` since the actual reject messages in the replica implementation deviate and could not be derived at the current abstraction level of the specification (e.g., currently we do not model subnet resource saturation).
=> fix: leave reject message as implementation-specific in the formal semantics

spec/_attachments/ic.did, spec/_attachments/interface-spec-changelog.md, spec/index.md
This PR introduces a new IC management canister method called `node_metrics_history` for retrieving history of metrics for all nodes on a given subnet.
=> specify IC management method for retrieving metrics

spec/_attachments/ic.did, spec/_attachments/interface-spec-changelog.md, spec/index.md
Context:
- https://forum.dfinity.org/t/23447
- https://dashboard.internetcomputer.org/proposal/126094
This adds new fields to the management canister interface:
- `reserved_cycles` to the result of `canister_status`.
- `reserved_cycles_limit` to `canister_settings` and `definite_canister_settings`.
The corresponding fields are also added to the abstract state:
- `reserved_balances`,
- `reserved_balance_limits`.
Note that the naming matches the exiting naming of the main cycle balance, which is `cycles` in the management canister and `balances` in the abstract state.
A new unspecified function `cycles_to_reserve` models cycle reservation for allocated resources depending on the old abstract state and the new state of the canister (and its new allocation settings).
Since the reserved cycles …
=> Specify the resource reservation mechanism

spec/_attachments/interface-spec-changelog.md, spec/index.md
This PR allows a system API method `in_replicated_execution` to be executed during `canister_start`.
=> feat: allow System API method in_replicated_execution to run during canister_start

spec/index.md
As discussed in various meetings, the nested certificate delegations allowed by the spec aren't used, but have complicated the reasoning about some features (see discussions around delegations in https://github.com/dfinity/interface-spec/pull/163 for example), and stating some properties (like the new subnet `read_state` requests). But we don't use nested delegations in practice and we don't have any plans to use them in the future. So this PR removes them.
=> Limit subnet certificate delegations to depth 1

spec/_attachments/ic.did, spec/index.md
This MR updates the specification of the `canister_status` management canister call that became outdated after recent additions of new fields into its response.
=> chore: update canister_status specs

spec/index.md
The chunk store is not part of `CanState` in this specification and thus this MR removes it from the definition of `CanState`.
=> fix: chunk_store is not part of CanState in this spec

spec/index.md
This MR fixes the access restrictions specified for the system API calls `ic0.data_certificate_{size,copy}` to be query and composite query methods. Since these calls always trap in any other method's context. Note that they also trap if `ic0.data_certificate_present()` returns 0, but this can't be encoded with the current access restriction matrix.
=> fix: ic0.data_certificate system API access restrictions

spec/_attachments/interface-spec-changelog.md, spec/index.md
This PR specifies the canister version to be incremented if the running status (Running, Stopping, Stopped) of a canister changes. The motivation for this change is that a canister can observe its running status through ic0.canister_status system API and thus query caching in the replica implementation based on canister version is unsound if the canister version does not reflect changes to the canister's running status.
=> feat: canister version guaranteed to increase if running status changes

spec/http-gateway-protocol-spec.md
This MR adds a note that composite query methods can be used instead of query methods in the HTTP gateway protocol and fixes a few typos/ambiguous formulations.
=> chore: add note on composite queries in HTTP gateway protocol

spec/index.md
The ordering guarantees specified in the spec are overpromising. The sender can't rely on the function calls being executed in order, and the calls are not really just like a FIFO queue, because there's no delivery guarantee for requests (the system can fail them at any time).
=> Fix the ordering guarantees claim.

spec/_attachments/interface-spec-changelog.md, spec/index.md
In the scope of the [IC-720: BN Decentralization Feature](https://forum.dfinity.org/t/boundary-node-roadmap/15562) we will need to be able to retrieve certified API boundary node domain names in a quick and easy way. The proposal is to modify the `State Tree` by introducing an `api_boundary_nodes` subtree (akin to [subnet-information](https://internetcomputer.org/docs/current/references/ic-interface-spec#state-tree-subnet)) holding all domain names, ipv4/ipv6 addresses.
=> feat: add api boundary nodes to state tree

spec/_attachments/ic.did, spec/_attachments/interface-spec-changelog.md, spec/index.md
This PR wraps a chunk hash in the management canister API into a record with a single field containing the hash and renames `storage_canister` to `store_canister`.
=> fix: wrap chunk hash in a record and rename storage_canister to store_canister

spec/_attachments/ic.did
This PR factors out the canister install mode from install_code and install_chunked_code argument definitions in the candid definitions.
=> chore: avoid canister install mode candid duplication

spec/index.md
This PR adds a note that cycles must be attached to calls to `sign_with_ecdsa`.
=> fix: add note on cycles for sign_with_ecdsa

spec/index.md
This PR adds a note that cycles must be attached to calls to create_canister.
=> fix: add note on cycles for create_canister

spec/index.md
This PR specifies the time unit of the IC time stored at the path `/time` in the system state tree.
=> fix: specify time unit of path /time

spec/index.md
This MR specifies that cycles attached to `provisional_top_up_canister` are refunded to the caller.
=> fix: refund cycles attached to provisional_top_up_canister

spec/_attachments/interface-spec-changelog.md, spec/index.md
The IC can currently reject requests at any point in time (e.g., because it's overloaded). But there is no corresponding transition in the spec currently.
=> fix: add spontaneous request rejection

spec/index.md
This PR fixes the specification of `ic0.call_new` that can't trap due to insufficient cycles (cycles for response execution are only checked in `ic0.call_perform`). Moreover, it makes the error code returned by `ic0.call_perform` implementation-specific to align with the actual replica implementation.
=> fix: ic0.call_new can't trap due to insufficient cycles

spec/_attachments/ic.did, spec/_attachments/interface-spec-changelog.md, spec/index.md
This PR adds an option (called `wasm_memory_persistence`) for canister upgrades. If this option is set, then the WebAssembly memory of the old canister is preserved across the upgrade.
=> [FINAL] feat: wasm_memory_persistence option for canister upgrades

spec/index.md
Replicated and non-replicated execution modes are already discussed in the spec but they are not formally specified. The two modes are already mentioned to distinguish the results of `ic0.data_certificate_*` calls and also in the case of the bitcoin query APIs on the management canister.
This PR formally introduces the concept of the two modes and updates the system API to be more explicit about when certain APIs are available in replicated vs non-replicated queries.
=> feat: Introduce replicated and non-replicated execution modes

spec/_attachments/ic.did, spec/_attachments/interface-spec-changelog.md, spec/index.md
The current name is confusing not only for me but also for the community member(s). I propose we change it to make it more specific.
link: https://matrix.to/#/!jUsknEqNdJobySpXuN:matrix.org/$wmamJVHU4QTXBWvNx-Rbq8NubEfHyAymhfdjMDsrWfU?via=matrix.org&via=greensteps.cn&via=rudd-o.com
=> fix: Correct the naming of the trustworthy metric: node num_blocks_total

spec/_attachments/ic.did, spec/_attachments/interface-spec-changelog.md, spec/index.md
This PR introduces a configurable WASM heap memory limit for canisters.
=> [FINAL] feat: WASM heap memory limit for canisters

spec/_attachments/interface-spec-changelog.md, spec/index.md
This PR deprecates the 32-bit stable memory System API which could make canisters trap if their stable memory size exceeds the 32-bit range.
=> chore: deprecate 32-bit stable memory System API

spec/_attachments/interface-spec-changelog.md, spec/index.md
This PR removes the management canister query calls `bitcoin_get_balance_query` and `bitcoin_get_utxos_query`. According to the metrics, they are not being used and the query call signature verification cannot be performed according to the specification (the read state request to fetch the replica public keys is gonna fail).
=> feat: remove bitcoin_get_balance_query and bitcoin_get_utxos_query

spec/index.md
This PR makes it explicit if external users may call management canister methods.
=> chore: make it explicit if external users may call management canister methods

spec/index.md
This PR fixes System API calls to add cycles to an inter-canister call:
- unify definitions of `ic0.call_cycles_add` and `ic0.call_cycles_add128` at one place in the section on inter-canister calls;
- return cycles transferred onto a call under construction if the canister returns without calling `ic0.call_perform`.
=> fix: System API calls to add cycles to an inter-canister call

spec/index.md
This PR fixes the specification of `ic0.call_new` and `ic0.call_on_cleanup` that do not validate the provided callback (in particular, since the canister can be upgraded before the callback is executed and thus the callback validation must be performed just before the callback is executed).
=> fix: ic0.call_new and ic0.call_on_cleanup do not validate callback

spec/index.md
This PR fixes the sentence "can only be called by ..., i.e., it cannot be called by ..., ..., and ..." by "can only be called by ..., i.e., it cannot be called by ..., cannot be called ..., and cannot be called ..." to make it unambiguous.
=> fix: make allowed callers of fetch_canister_logs unambiguous

spec/index.md
This MR adds a note on the mgmt canister fetch logs API that no logs are collected for methods running in non-replicated mode.
=> chore: note on canister logs not collected in non-replicated mode

.gitignore, docusaurus/package-lock.json, docusaurus/package.json, spec/index.md
- Update all headings to use `{#heading}` syntax
- Fix broken links where the heading name was changed
- Update docusaurus version to latest
=> chore: fix broken links in headings

spec/index.md
This PR simplifies the definition of the `Delegation` type which is a simple record type and thus there's no need to formally define it as an enumeration type with a single variant `Delegation`.
=> fix: simplify definition of Delegation type

spec/index.md
Moving the method description to the suitable subsection (it's not part of the Bitcoin API).
=> chore: Move fetch_canister_logs to main management canister subsection

spec/index.md
This PR fixes the specification to drop the chunk store of a deleted canister. The implementation removes the chunk store by removing the entire canister from the replicated state including the chunk store stored in the canister's system state.
=> fix: chunk store of a deleted canister is dropped

spec/_attachments/ic.did, spec/_attachments/interface-spec-changelog.md, spec/index.md
As part of [IC-1666](https://dfinity.atlassian.net/browse/IC-1666) the proposal introduces a new HTTPS endpoint for synchronous update calls, or "call and await", where users can send call requests to the replica and get the response back in the same request. This differs from the current call approach where users have to continuously poll the status of a call request to get the response.
Adding a synchronous endpoint for update calls will significantly decrease the end-to-end (client-observed) latency for update calls. An initial prototype shows that the client-observed latency can be reduced by a minimum of 1 second which is ~40% improvement.
[IC-1666]: https://dfinity.atlassian.net/browse/IC-1666?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cif …
=> feat(sync-call): [IC-1666] Endpoint for synchronous call requests

docusaurus/package-lock.json
Bumps [cookie](https://github.com/jshttp/cookie) and [express](https://github.com/expressjs/express). These dependencies needed to be updated together.
Updates `cookie` from 0.6.0 to 0.7.1
- [Release notes](https://github.com/jshttp/cookie/releases)
- [Commits](https://github.com/jshttp/cookie/compare/v0.6.0...v0.7.1)
Updates `express` from 4.21.0 to 4.21.1
- [Release notes](https://github.com/expressjs/express/releases)
- [Changelog](https://github.com/expressjs/express/blob/4.21.1/History.md)
- [Commits](https://github.com/expressjs/express/compare/4.21.0...4.21.1)
---
updated-dependencies:
- dependency-name: cookie dependency-type: indirect
- dependency-name: express dependency-type: indirect ...
=> chore(deps): bump cookie and express in /docusaurus

spec/index.md
This PR fixes issues in `ic0.call_perform` spec:
- adds one more condition under which a call successfully finalized by `ic0.call_perform` might still fail;
- specifies that discarding a pending call does not refund the prepayment for execution since this prepayment is not charged for a pending call.
=> fix: ic0.call_perform spec

spec/index.md
This PR specifies the effective canister ID for the `install_chunked_code` method of the management canister whose candid argument does not have a `canister_id` field.
=> fix: specify effective canister id for install_chunked_code

spec/_attachments/interface-spec-changelog.md, spec/index.md
This PR allows anonymous `query` and `read_state` requests with invalid `ingress_expiry`. The motivation is to allow users retrieving the certified subnet time via an anonymous read state request without having to provide a valid `ingress_expiry` (which they might not be able to do if they don't know the subnet time).
=> feat: allow anonymous query and read_state requests with invalid ingress_expiry

spec/_attachments/ic.did, spec/_attachments/interface-spec-changelog.md, spec/index.md
This PR adds `allowed_viewers` variant to canister's `log_visibility` which allows to fetch logs by specified number of principals.
=> [FINAL] feat: [EXC-1676] add allowed viewers variant to canister's log visibility
